name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'website/**'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - 'package.json'
      - 'yarn.lock'
      - 'tools/release'

  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'website/**'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - 'package.json'
      - 'yarn.lock'
      - 'tools/release'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "license-rc"
  license-rc:
    name: License header
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main

  # This workflow compile the project on Windows without running any test
  compile:
    name: Windows Compile
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    defaults:
      run:
        shell: cmd
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Setup Apache Thrift Compiler
        run: |
          mkdir thrift
          cd thrift
          certutil -urlcache -split -f http://archive.apache.org/dist/thrift/0.13.0/thrift-0.13.0.exe thrift.exe
          dir /b /s
          set path=%path%;D:\a\bitsail\bitsail\thrift
          thrift -version

      - name: Compile
        run:
          mvn clean verify -pl bitsail-dist -am -DskipUT=true -DskipITCase=true

  # This workflow contains a single job called "macos-unit-test"
  macos-unit-test:
    name: MacOS Unit Test
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Setup Apache Thrift Compiler
        run: |
          brew tap-new $USER/local-tap
          brew extract --version='0.13.0' thrift $USER/local-tap
          brew install thrift@0.13.0
          thrift -version

      - name: Maven Verify Unit Test
        run:
          mvn clean verify -pl bitsail-dist -am -DskipUT=false -DskipITCase=true

  # This workflow contains a single job called "ubuntu-unit-test"
  ubuntu-unit-test:
    name: Ubuntu Unit Test
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Setup Apache Thrift Compiler
        uses: dodopizza/setup-thrift@v1
        with:
          version: 0.13.0

      - name: Maven Verify Unit Test
        run:
          mvn clean verify -pl bitsail-dist -am -DskipUT=false -DskipITCase=true

    # This workflow contains a single job called "integration-tests"
  integration-tests:
    name: Integration Test
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Setup Apache Thrift Compiler
        uses: dodopizza/setup-thrift@v1
        with:
          version: 0.13.0

      - name: Maven Verify Integration Test
        run:
          mvn clean verify -pl bitsail-dist -am -DskipUT=true -DskipITCase=false
